### ISSUE TITLE
Enter color through gui

### ISSUE THREAD

**Issue by musm** [ahmetcecen/IsoSlicer-MATLAB#1]
Would be great if had the option to enter the r,g,b index or hex # of a color directly above or below the sliders. It's hard to slide to get exactly the color you need using the sliders.

Thanks

**Comment by ahmetcecen** [comment]
I will look into implementing this within a week or so, depending on free time. In the mean time, I would really appreciate if you share your use case, how you found the tool etc. with me so I can improve documentation, tags etc and understand different needs. You can either share it here or send me a private e-mail at ahmetcecen@gmail.com whichever is comfortable. Also please rate the submission at the file exchange when you get a chance:

http://www.mathworks.com/matlabcentral/fileexchange/55635-isoslicer

**Comment by musm** [comment]
No problem. Great tool, I just needed to visualize 3d data and your package was very easy to use. I tried to rate your package, but the rating tool doesn't work? 
Thanks for taking a look at this. It's great to be able to have exact control on the colors of the iso-surfaces for publication purposes.

**Comment by ahmetcecen** [comment]
Check it out now.

**Comment by musm** [comment]
Thanks! Works great. Closing this now.
