### ISSUE TITLE
There is no button on the interface

### ISSUE THREAD

**Issue by JunMa11** [ahmetcecen/IsoSlicer-MATLAB#2]
Thank you for sharing the code.
when I write IsoSlicer to the command window, There is no button on the interface.
![no button](http://i4.piimg.com/595387/b2285ca4faf87b50.png)

**Comment by ahmetcecen** [comment]
This is an old GUI with a hard coded size. It will only be fully visible beyond a certain resolution.  What is the resolution of your screen?

**Comment by JunMa11** [comment]
Thanks for your quick reply.
The resolution of your screen is 1920*1080;
In addition, the version of my matlab is 2015b.
Would it be possible for you to tell me how to change the code to fit my screen's resoluton?

**Comment by ahmetcecen** [comment]
Try it now. It should be re-sizable.

**Comment by JunMa11** [comment]
It works. Great tool, thank you.
